version: "3.8"
services:
  bot:
    build:
      dockerfile: Dockerfile
    container_name: notion-bot
    env_file:
      - ./.env
    environment:
      REDIS_URL: redis://redis
    depends_on:
      - redis
    restart: always
    networks:
      notion-bot-network:
  redis:
    image: redis:alpine
    command:
      - redis-server
    ports:
      - "6379:6379"
    container_name: main_Redis
    volumes:
      - redis-data:/data/
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      notion-bot-network:
networks:
  notion-bot-network:
    name: notion-bot-network
    driver: bridge
    internal: false
    attachable: true
volumes:
  redis-data:
  redis-conf:
